version: "3.9"

networks:
  no_games_hub:

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: "${APP_NAME}-server"
    ports:
      - "${APP_PORT}:80"
    working_dir: /var/www/html
    environment:
      - "DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@db_server:3306/${DB_DATABASE}?serverVersion=10.7"
    volumes:
      - ./:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - no_games_hub

  db_server:
    image: mariadb:10.7.1
    container_name: "${APP_NAME}-db"
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$DB_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - no_games_hub

volumes:
  db_data:
